Revert "/root/G/SCA_SDO-1.2.4/sdo.cpp:82: error: âfunction_entryâ does not name a type"
This reverts commit 25eef4cb6f93f5b2f98ed5630bd4a01d9cce914e.