Revert "/root/G/SCA_SDO-1.2.4/sdo.cpp:86: error: âfunction_entryâ does not name a type"
This reverts commit 914c4383887f59b5ae37962e6da186e93df9e79f.