Revert "/root/G/SCA_SDO-1.2.4/sdo.cpp:82: error: âfunction_entryâ does not name a type"
This reverts commit dad7d73b4b2fe4083b6edb549d39224239799aeb.