Revert "/root/G/SCA_SDO-1.2.4/sdo.cpp:87: error: âfunction_entryâ does not name a type"
This reverts commit 871c1e85b7a00d2e704b933ef41c8ff8e4f39aa9.