Revert "/root/G/SCA_SDO-1.2.4/sdo.cpp:85: error: âfunction_entryâ does not name a type"
This reverts commit fdba6f96edea54a11d93261d79d72ba9fdc41292.