Revert "/root/G/SCA_SDO-1.2.4/sdo.cpp:90: error: âfunction_entryâ does not name a type"
This reverts commit 49837946977397c61574e9a9cea8c0483f68ea33.